### ISSUE TITLE
Item Tooltips Display Internal Names

### ISSUE THREAD

**Issue by Lurrae** [gigaherz/JsonThings#22]
When using a mod like Jade that displays the source mod of a block or mob you're looking at, or any mod that displays mod origins in an item's tooltip (which might just be a default Forge feature? Not sure), items from a thingpack display the internal namespace of the thingpack (for example, `no_loose_ends`) instead of the display name of the thingpack (for example, `No Loose Ends`)

**Comment by gigaherz** [comment]
These mods look up the mod name from the Forge-provided mod info. This info is read from the mods.toml metadata, and cannot be provided by other means. So that means this can only work if the thingpack is packaged as a mod jar file along with a mods.toml file, and placed in the mods folder.

Hmm, although this got me thinking of a really bad idea that probably won't work.
