### ISSUE TITLE
[1.21] Jsonthing crash with Solarflux latest build.

### ISSUE THREAD

**Issue by Periam** [gigaherz/JsonThings#36]
Installing the latest version of Jsonthing and SolarFlux, the game crashed

MC 1.21
Neoforge-21.0.164
SolarFluxReborn-1.21-21.0.3
Jsaonthing-1.21-0.12.1
hammerlib-1.21-21.0.13
jei-1.21-neoforge-19.7.0.91

[debug.log](https://github.com/user-attachments/files/16529557/debug.log)
[latest.log](https://github.com/user-attachments/files/16529558/latest.log)
[crash-2024-08-07_10.36.54-fml.txt](https://github.com/user-attachments/files/16529562/crash-2024-08-07_10.36.54-fml.txt)

**Comment by gigaherz** [comment]
Hi, Json Things uses a custom resource manager that loads before registry events. This is necessary for Json Things to work, but some mods don't expect this to happen and crash. It seems Solar Flux is one of those mods.
You should report this to solar flux, so that they can choose if they want to only register reload listeners for a well-known PackTypes (instead of doing the initialization unconditionally), or they want to protect their loading logic so that it is skipped for unknown pack types only if it runs too early.

**Comment by Periam** [comment]
thanks I will..
